[package]
name = "theyrefor-server"
version = "0.1.0"
edition = "2024"

[dependencies]
theyrefor-models = { path = "../models", features = ["twilight-model"] }

base64 = { workspace = true }
bincode = { workspace = true }
err-into = { workspace = true }
http = { workspace = true }
log = { workspace = true }

async-trait = "0.1"
futures = "0.3"
itertools = "0.14"
moka = { version = "0.12", features = ["future"] }
mime = "0.3"
rand = "0.10.1"
reqwest = { version = "0.13", features = ["blocking", "json"] }
rocket = { version = "0.5", features = ["json", "secrets" ] }
serde = { workspace = true, features = ["derive" ] }
serde_millis = "0.1"
serde_json = "1.0"
serde_urlencoded = "0.7"
twilight-http = "0.17"
twilight-model = "0.17"
urlencoding = "2.1"
