[package]
name = "theyrefor-models"
version = "0.1.0"
edition = "2021"
authors = ["Isaac M. Good <imgood@imgoodproductions.org>"]

[dependencies]
serde = "1.0"
twilight-model = { version = "0.14", optional = true }